# Generated by Django 5.2.7 on 2025-11-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_rename_tamanio_particula_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='energia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='energia/'),
        ),
        migrations.AddField(
            model_name='particula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='particula/'),
        ),
    ]
