# Generated by Django 5.2.7 on 2025-11-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_energia_imagen_particula_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inicio/')),
            ],
        ),
        migrations.RemoveField(
            model_name='particula',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='energia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='energia'),
        ),
    ]
