# Generated by Django 5.2.7 on 2025-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_inicio_remove_particula_imagen_alter_energia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenInicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inicio/')),
            ],
        ),
        migrations.DeleteModel(
            name='inicio',
        ),
    ]
