# Generated by Django 5.2.7 on 2025-11-21 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
    ]
