# Generated by Django 5.2.7 on 2025-11-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_cv_bio_remove_cv_estudios_cv_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='estudios_realizados',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='experiencia_laboral',
            field=models.TextField(default=''),
        ),
    ]
