# Generated by Django 5.2.7 on 2025-11-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cv_estudios_realizados_cv_experiencia_laboral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='estudios_realizados',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experiencia_laboral',
        ),
        migrations.AddField(
            model_name='cv',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cv/'),
        ),
    ]
